services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wellnest
      SECRET_KEY: oqPGmcEK7DAidmVc9SlSctx5yUr9sJEM8ROUSfml3wc
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      PROJECT_NAME: WellNest API
      PROJECT_DESCRIPTION: API for WellNest Health Management System
      VERSION: 1.0.0
      PORT: 8000
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wellnest
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
